import type { InkosEndpoint } from "../types.js";

export const OPENAI_ENDPOINTS: readonly InkosEndpoint[] = [
  {
    id: "openai",
    label: "OpenAI",
    providerFamily: "openai",
    baseUrl: "https://api.openai.com/v1",
    transportDefaults: { apiFormat: "responses", stream: true },
    models: [],
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    providerFamily: "openai",
    baseUrl: "https://api.deepseek.com",
    transportDefaults: { apiFormat: "chat", stream: true },
    models: [],
  },
  {
    id: "moonshot",
    label: "Moonshot (Kimi)",
    providerFamily: "openai",
    baseUrl: "https://api.moonshot.cn/v1",
    transportDefaults: { apiFormat: "chat", stream: true },
    models: [],
  },
  {
    id: "zhipu",
    label: "智谱 GLM",
    providerFamily: "openai",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    transportDefaults: { apiFormat: "chat", stream: true },
    models: [],
  },
  {
    id: "siliconflow",
    label: "硅基流动",
    providerFamily: "openai",
    baseUrl: "https://api.siliconflow.cn/v1",
    transportDefaults: { apiFormat: "chat", stream: true },
    models: [],
  },
  {
    id: "ppio",
    label: "PPIO",
    providerFamily: "openai",
    baseUrl: "https://api.ppinfra.com/v3/openai",
    transportDefaults: { apiFormat: "chat", stream: true },
    models: [],
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    providerFamily: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    transportDefaults: { apiFormat: "responses", stream: true },
    models: [],
  },
  {
    id: "ollama",
    label: "Ollama (本地)",
    providerFamily: "openai",
    baseUrl: "http://localhost:11434/v1",
    transportDefaults: { apiFormat: "chat", stream: true },
    models: [],
  },
  {
    id: "custom",
    label: "自定义端点",
    providerFamily: "openai",
    baseUrl: "",
    transportDefaults: { apiFormat: "chat", stream: true },
    models: [],
  },
];
